In [1]:
import pandas as pd

df = pd.read_csv("vehicle0_1.csv")
df

,Attr1,Attr2,Attr3,Attr4,Attr5,Attr6,Attr7,Attr8,Attr9,Attr10,Attr11,Attr12,Attr13,Attr14,Attr15,Attr16,Attr17,Attr18,class
0,85,45,80,154,64,9,147,45,19,148,169,324,174,71,1,4,188,199,1
1,93,40,73,139,58,6,136,49,18,138,166,275,137,73,0,0,187,188,1
2,86,40,66,139,59,7,122,54,17,139,145,225,143,63,7,11,202,208,1
3,91,38,70,160,66,25,140,47,18,139,162,296,130,67,4,11,192,202,1
4,98,38,66,130,55,7,130,51,18,138,160,251,123,69,3,12,191,194,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,90,48,78,134,56,11,160,43,20,167,169,366,185,76,1,14,182,192,1
195,92,40,62,144,59,8,127,52,17,139,149,241,150,62,13,1,204,210,1
196,85,47,75,121,53,9,157,44,20,165,168,358,176,77,1,7,182,191,1
197,93,43,78,162,64,8,137,48,18,145,156,281,159,63,17,12,203,210,1
198,89,47,84,133,55,11,157,44,20,160,169,354,176,74,5,9,182,192,1

In [12]:
df2 = df[["Attr{}".format(i) for i in [4,5,12]]]
df2.to_csv("vehicle0_1_lite.csv", sep=",", index=False)

In [13]:
df2 = pd.read_csv("vehicle0_1_lite.csv")
df2

     Attr4  Attr5  Attr12
0      154     64     324
1      139     58     275
2      139     59     225
3      160     66     296
4      130     55     251
..     ...    ...     ...
194    134     56     366
195    144     59     241
196    121     53     358
197    162     64     281
198    133     55     354

[199 rows x 3 columns]